config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "stories#index"
  resources :stories, except: [:show] 

end

app/models/story.rb
class Story < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable#, :recoverable
  has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
    before_action :find_story, only: [:edit, :update, :destroy]
	before_action :authenticate_user!

	def index
		@stories = Story.all
	end

	def new
		@story = current_user.stories.build
	end

	def create
		@story = current_user.stories.build(story_params)

		if @story.save
			redirect_to stories_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @story.update(story_params)
			redirect_to stories_path
		else
			render 'edit'
		end
	end

	def destroy
		@story.destroy
		redirect_to root_path
	end

	private

	def find_story
		@story = Story.find(params[:id])
	end

	def story_params
		params.require(:story).permit(:title, :story, :quote, :author)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,700" rel="stylesheet">
</head>
<body>
<% if flash[:notice] || flash[:alert] %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% end %>
<%= image_tag("Stories.png") %>
<nav>
  <section><%= link_to 'Me', edit_user_registration_path %></section>
  <section></section>
  <section><%= link_to 'New', new_story_path %></section>
  <section>INVISIBLE SECTION W/ STYLES</section>
  <section></section>
  <section><%= link_to 'Logout', destroy_user_session_path, method: :delete %></section>
</nav>

<%= yield %>

</body>
</html>

app/views/stories/_form.html.erb
<div class="container">
<%= simple_form_for @story do |s| %>
    <%= s.input :title %>
    <%= s.input :story, as: :text %>
    <%= s.input :quote %>
    <%= s.input :author %>
    <%= s.submit %>
<% end %>
</div>

app/views/stories/edit.html.erb
<%= render 'form' %>

app/views/stories/index.html.erb
<div class="wrap container">
    <div id="tinderslide">
        <ul>
            <% @stories.each do |s| %>
                <li class="pane<%= s.id %>">
                    <div class="tcard">
                    <div class="title">
                        <h4><%= s.title %></h4>
                        <span class="rating">Yas</span>
                        <span class="rating">Nas</span>
                        <div class="author">Author: <h5><%= s.author %></h5></div>
                    </div>
                    <div class="story"><%= s.story %></div>
                    <div class="buttonct">
                        <%= link_to 'Destroy', s, method: :delete, confirm: 'Are you sure?', class: "button"  %>
                        <%= link_to 'Edit', edit_story_path(s), class: "button" %>
                    </div>
                </li>
            <% end %>
        </ul>
    </div>
</div>

<script type="javascript">
$("#tinderslide").jTinder({
	animationRevertSpeed: 200,
	animationSpeed: 100,
});
</script>
<script>$("#tinderslide").jTinder();</script>

app/views/stories/new.html.erb
<%= render 'form' %>